# Composicao do programa de teste de um Grafo
# Este exemplo utiliza o arcabouco completo 

[Diretorios]

Nome        =  TesteArvoreDebug
PathDefault =  ..\Fontes
err         =  ..\Produto
obj         =  ..\Objetos
c           =  ..\Fontes
h           =  ..\Fontes
def         =  ..\Tabelas

[Modulos]
Lista			
TESTGRA			/D_DEBUG
Grafo 			/D_DEBUG

[BuildInicio]
/OUT:TesteGrafoDebug.exe
/INCREMENTAL:NO
/MACHINE:IX86

[BuildFim]
ArcaboucoTeste.lib

[Fim]
