# Composicao do programa de teste de um Grafo
# Este exemplo utiliza o arcabouco completo 

[Diretorios]

Nome        =  TesteMensagem
PathDefault =  ..\Fontes
err         =  ..\Produto
obj         =  ..\Objetos
c           =  ..\Fontes
h           =  ..\Fontes
def         =  ..\Tabelas

[Modulos]
TestMen
Mensagem


[BuildInicio]
/OUT:..\produto\TesteMensagem.exe
/INCREMENTAL:NO
/MACHINE:IX86

[BuildFim]
ArcaboucoTeste.lib

[Fim]
